services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: water-flow-control
      POSTGRES_PASSWORD: water-flow-control
      POSTGRES_DB: water-flow-control
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

